name: Github Pages

on:
  workflow_dispatch:
  schedule:
    # run at 8,10,12,14,16 hour every day CST
    - cron: '0 0,2,4,6,8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Load
        run: ./load.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          # force_orphan: true
